name: Deploy

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Setup SSH
              uses: shimataro/ssh-key-action@v2
              with:
                key: ${{ secrets.EC2_SSH_KEY }}
                known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
            - name: Adding Known Hosts
              run: ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

            - name: Run Pre-Deploy script
              uses: appleboy/ssh-action@v0.1.10
              with:
                host: ${{ secrets.REMOTE_HOST }}
                username: ${{ secrets.REMOTE_USER }}
                key: ${{ secrets.EC2_SSH_KEY }}
                command_timeout: 30m
                script: |
                  sudo bash /home/ubuntu/kogo/scripts/pre-deploy.sh

            - name: Deploy to test server
              run:
                rsync -vrm --exclude={'node_modules'} . ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/ubuntu/kogo/kogo-cms

            - name: Run Post-Deploy script
              uses: appleboy/ssh-action@v0.1.10
              with:
                host: ${{ secrets.REMOTE_HOST }}
                username: ${{ secrets.REMOTE_USER }}
                key: ${{ secrets.EC2_SSH_KEY }}
                command_timeout: 30m
                script: |
                  sudo bash /home/ubuntu/kogo/scripts/post-deploy.sh

