name: Deploy

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - name: Deploy to test server
              uses: easingthemes/ssh-deploy@main
              with:
                  SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
                  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                  REMOTE_USER: ${{ secrets.REMOTE_USER }}
                  TARGET: "/home/ubuntu/kogo/kogo-cms"
                  EXCLUDE: "/dist/, /node_modules/"
                  SCRIPT_BEFORE: |
                    whoami
                    bash /home/ubuntu/kogo/scripts/archive.sh
                  SCRIPT_AFTER: |
                    ls -al
                    bash /home/ubuntu/kogo/scripts/start.sh

