name: Run Test

on: [push]

env:
  NODE_ENV: development
  APP_KEYS: testappkey
  TRANSFER_TOKEN_SALT: testtransfertokensalt
  ADMIN_JWT_SECRET: testadminjwtsecret
  API_TOKEN_SALT: testapitokensalt
  JWT_SECRET: testjwtsecret

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x, 18.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - name: Install Dependencies
              run: npm install

            - name: Create a Strapi build for testing
              run: NODE_ENV=development npm run build

            - name: Run Test
              run: CI=true npm run test
